### ISSUE TITLE
Add helper text for the sign-up modal

### ISSUE THREAD

**Issue by the-turk** [the-turk/flarum-regrole#1]
https://discuss.flarum.org/d/24500-registration-roles/5

> May I suggest adding some helper text for the sign-up modal right before the groups themselves? It wouldn't be clear to new users IMO what those cards are until the validator hints at them to select a role. Maybe just copy and paste the same translation key for "Choose A Role"?

**Comment by Ralkage** [comment]
I forked this extension and tried to add a label only for the Sign Up modal but I don't know how to check if the current model is the Sign Up Modal to begin with.

Would you know the best way to check for this?

**Comment by the-turk** [comment]
hey @Ralkage it's been a year 😄 

Screenshot from this commit:

![](https://i.imgur.com/4h9wmUH.png)

It will show up only on Sign Up modal and fully customizable via css.
