### ISSUE TITLE
Registration roles not showing on modals

### ISSUE THREAD

**Issue by katosdev** [the-turk/flarum-regrole#13]
Users seem to be unable to select registration roles on my forum.
The flexbox div is empty:

`<div class="regRole-container"></div>`

Details as follows:
- Flarum V1.0.4
- Extension version 1.0.2
- four registration roles available to pick.
- Cache cleared / Apache restarted.

I can submit further details if required.
Cross-posted to discuss : https://discuss.flarum.org/d/24500-registration-roles/39

**Comment by the-turk** [comment]
Thanks! Should be fixed on 1.0.3
